In [1]:
pip install gensim

  Obtaining dependency information for FuzzyTM>=0.4.0 from https://files.pythonhosted.org/packages/2d/30/074bac7a25866a2807c1005c7852c0139ac22ba837871fc01f16df29b9dc/FuzzyTM-2.0.9-py3-none-any.whl.metadata
  Obtaining dependency information for pyfume from https://files.pythonhosted.org/packages/ed/ea/a3b120e251145dcdb10777f2bc5f18b1496fd999d705a178c1b0ad947ce1/pyFUME-0.3.4-py3-none-any.whl.metadata
  Obtaining dependency information for scipy>=1.7.0 from https://files.pythonhosted.org/packages/0d/3e/d05b9de83677195886fb79844fcca19609a538db63b1790fa373155bc3cf/scipy-1.10.1-cp311-cp311-macosx_12_0_arm64.whl.metadata
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100.1/100.1 kB 1.6 MB/s eta 0:00:00a 0:00:01
  Obtaining dependency information for numpy>=1.18.5 from https://files.pythonhosted.org/packages/c0/bc/77635c657a3668cf652806210b8662e1aff84b818a55ba88257abf6637a8/numpy-1.24.4-cp311-cp311-macosx_11_0_arm64.whl.metadata
  Obtaining dependency information for simpful==2.12.0 from https:

In [2]:
import gensim.downloader as api
model = api.load("word2vec-google-news-300")

[==================================================] 100.0% 1662.8/1662.8MB downloaded


In [3]:
words_vector = model
print(words_vector['computer']) # example of computer

[ 1.07421875e-01 -2.01171875e-01  1.23046875e-01  2.11914062e-01
 -9.13085938e-02  2.16796875e-01 -1.31835938e-01  8.30078125e-02
  2.02148438e-01  4.78515625e-02  3.66210938e-02 -2.45361328e-02
  2.39257812e-02 -1.60156250e-01 -2.61230469e-02  9.71679688e-02
 -6.34765625e-02  1.84570312e-01  1.70898438e-01 -1.63085938e-01
 -1.09375000e-01  1.49414062e-01 -4.65393066e-04  9.61914062e-02
  1.68945312e-01  2.60925293e-03  8.93554688e-02  6.49414062e-02
  3.56445312e-02 -6.93359375e-02 -1.46484375e-01 -1.21093750e-01
 -2.27539062e-01  2.45361328e-02 -1.24511719e-01 -3.18359375e-01
 -2.20703125e-01  1.30859375e-01  3.66210938e-02 -3.63769531e-02
 -1.13281250e-01  1.95312500e-01  9.76562500e-02  1.26953125e-01
  6.59179688e-02  6.93359375e-02  1.02539062e-02  1.75781250e-01
 -1.68945312e-01  1.21307373e-03 -2.98828125e-01 -1.15234375e-01
  5.66406250e-02 -1.77734375e-01 -2.08984375e-01  1.76757812e-01
  2.38037109e-02 -2.57812500e-01 -4.46777344e-02  1.88476562e-01
  5.51757812e-02  5.02929

In [ ]:
print(words_vector['Arif']) #300 dimension

[-0.1796875   0.40039062  0.07910156 -0.1171875   0.17871094  0.09814453
  0.15820312 -0.27734375 -0.17871094  0.05004883 -0.14648438  0.12988281
 -0.18945312  0.07226562 -0.3125      0.07373047  0.04663086 -0.3125
  0.14453125  0.15136719 -0.18261719 -0.01275635 -0.05151367  0.06933594
  0.13183594  0.05297852 -0.06494141 -0.15136719  0.05932617 -0.13574219
 -0.28515625 -0.21289062  0.07226562  0.16210938  0.0078125   0.12353516
 -0.0402832   0.05786133 -0.02355957 -0.16894531  0.12890625 -0.05834961
  0.04296875  0.04296875  0.09130859 -0.17773438 -0.12988281 -0.20703125
  0.05371094 -0.2890625   0.11035156  0.12109375  0.20507812 -0.00500488
 -0.140625    0.03759766 -0.25390625  0.14648438 -0.14160156 -0.27929688
  0.02563477 -0.25585938 -0.1328125  -0.08154297  0.03637695  0.10302734
  0.35742188 -0.13085938  0.11279297 -0.06176758 -0.26171875  0.140625
 -0.12597656 -0.06787109 -0.24609375 -0.28710938  0.15136719 -0.02026367
  0.19140625 -0.18847656  0.10693359  0.08300781 -0.01843

In [5]:
print(words_vector['Arif'].shape)

(300,)


In [6]:
# Symentic words capturing
# King + Woman - Man = ?
# Example of using most_similar
print(words_vector.most_similar(positive = ['king', 'woman'], negative = ['man'], topn = 10)) 

[('queen', 0.7118192911148071), ('monarch', 0.6189674735069275), ('princess', 0.5902431011199951), ('crown_prince', 0.5499460697174072), ('prince', 0.5377321243286133), ('kings', 0.5236844420433044), ('Queen_Consort', 0.5235945582389832), ('queens', 0.5181134343147278), ('sultan', 0.5098593235015869), ('monarchy', 0.5087411403656006)]


In [ ]:
#
print(words_vector.similarity('dog', 'puppy'))

0.81064284


In [13]:
#similar word finding
print(words_vector.most_similar('albedo', topn=3))

[('reflectivity', 0.6868868470191956), ('atmospheric_aerosols', 0.6233901381492615), ('cosmic_ray_flux', 0.620396077632904)]


In [14]:
import numpy as np
#words compare
word1 = 'man'
word2 = 'woman'

word3 = 'semiconductor'
word4 = 'earthworm'

word5 = 'nephew'
word6 = 'niece'

#Calculate the vector difference
vector_difference1 = model[word1] - model[word2]
vector_difference2 = model[word3] - model[word4]
vector_difference3 = model[word5] - model[word6]

# Calculate the magnitude of the vector difference
magnitude_of_difference1 = np.linalg.norm(vector_difference1)
magnitude_of_difference2 = np.linalg.norm(vector_difference2)
magnitude_of_difference3 = np.linalg.norm(vector_difference3)

#Print the magnitude of the difference
print("The magnitude of the difference between '{}' and  '{}' is {: .2f}" .format(word1, word2, magnitude_of_difference1))
print("The magnitude of the difference between '{}' and  '{}' is {: .2f}" .format(word3, word4, magnitude_of_difference2))
print("The magnitude of the difference between '{}' and  '{}' is {: .2f}" .format(word5, word6, magnitude_of_difference3))

The magnitude of the difference between 'man' and  'woman' is  1.73
The magnitude of the difference between 'semiconductor' and  'earthworm' is  5.67
The magnitude of the difference between 'nephew' and  'niece' is  1.96


In [15]:
# Let's  see how token id is converted to embadding vector conversion. we assume four input tokens with IDs 2,3,5
import torch

In [16]:
inputs_ids = torch.tensor([2,3,5,1])

In [ ]:
#initilizing random number of weights
vocab_size = 6
output_dim = 3
torch.manual_seed(123)
embedding_layer = torch.nn.Embedding(vocab_size,output_dim)

In [19]:
print(embedding_layer.weight)

Parameter containing:
tensor([[ 0.3374, -0.1778, -0.1690],
        [ 0.9178,  1.5810,  1.3010],
        [ 1.2753, -0.2010, -0.1606],
        [-0.4015,  0.9666, -1.1481],
        [-1.1589,  0.3255, -0.6315],
        [-2.8400, -0.7849, -1.4096]], requires_grad=True)


In [20]:
# we look up at the perticular id
print(embedding_layer(torch.tensor([3])))

tensor([[-0.4015,  0.9666, -1.1481]], grad_fn=<EmbeddingBackward0>)


In [ ]:
# It is exacly same as fourth row

In [21]:
print(embedding_layer(inputs_ids))

tensor([[ 1.2753, -0.2010, -0.1606],
        [-0.4015,  0.9666, -1.1481],
        [-2.8400, -0.7849, -1.4096],
        [ 0.9178,  1.5810,  1.3010]], grad_fn=<EmbeddingBackward0>)
